// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Keep public pages renderable in local previews where deployment variables
// have not been injected yet. Auth/data requests will fail normally until the
// real values are configured, rather than crashing the application at import.
const CLIENT_URL = SUPABASE_URL || 'http://127.0.0.1:54321';
const CLIENT_KEY = SUPABASE_PUBLISHABLE_KEY || 'preview-anon-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(CLIENT_URL, CLIENT_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
